/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import appLogger.AppLog;
import appLogger.LogType;
import controllollers.Auth;

import java.sql.SQLException;
import javax.swing.JOptionPane;
import models.Product;
import models.User;
import modes.Roles;
import java.io.IOException;
import java.util.Date;

import java.io.File;
import java.time.LocalDateTime;

/**
 *
 * @author vidur
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
   

    public Login() {
        initComponents();
        buttonGroupRoleMode.setSelected(jRB_cachier.getModel(), rootPaneCheckingEnabled);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupRoleMode = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        tf_email = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tf_password = new javax.swing.JPasswordField();
        jRB_cachier = new javax.swing.JRadioButton();
        jRB_admin = new javax.swing.JRadioButton();
        btn_login = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Sithara Super Center");

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setText("Email");

        tf_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_emailActionPerformed(evt);
            }
        });

        jLabel3.setText("Password");

        tf_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_passwordActionPerformed(evt);
            }
        });

        buttonGroupRoleMode.add(jRB_cachier);
        jRB_cachier.setText("Cashier");

        buttonGroupRoleMode.add(jRB_admin);
        jRB_admin.setText("admin");
        jRB_admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRB_adminActionPerformed(evt);
            }
        });

        btn_login.setText("Login");
        btn_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_loginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jRB_cachier)
                                .addGap(18, 18, 18)
                                .addComponent(jRB_admin))
                            .addComponent(tf_email, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_password, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_login))))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tf_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tf_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRB_cachier)
                    .addComponent(jRB_admin))
                .addGap(18, 18, 18)
                .addComponent(btn_login)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(117, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(115, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(68, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tf_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_emailActionPerformed

    private void tf_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_passwordActionPerformed

    private void jRB_adminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRB_adminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRB_adminActionPerformed

    private void btn_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_loginActionPerformed
        String email = tf_email.getText();
        String password = tf_password.getText();

        User user = new User();
        user.setEmail(email);
        user.setPassword(password);

        if (jRB_admin.isSelected()) {
            user.setRole(Roles.ADMIN);
        } else {
            user.setRole(Roles.CASHIER);
        }
        Auth auth = new Auth(user);

        try {

            if (auth.isAuthUser()) {
                this.dispose();
                if (auth.isDev()) {
                    appLogger.WriteLog.log(new AppLog(LocalDateTime.now().toString(), Login.class.getName(), "DEVELOPER LOGIN", Roles.DEVELOPER.name(), LogType.WARN));
                    JOptionPane.showMessageDialog(this, "You accessing Developer Dashboard", "WARNING", JOptionPane.WARNING_MESSAGE);
                    DevDashboard dev = new DevDashboard(auth);
                    dev.setVisible(true);

                } else {
                    if (auth.isAdmin()) {
                        appLogger.WriteLog.log(new AppLog(LocalDateTime.now().toString(), Login.class.getName(), "ADMIN LOGIN", Roles.ADMIN.name(), LogType.INFO));
                       
                    }
                    if (auth.isCashier()) {
                        appLogger.WriteLog.log(new AppLog(LocalDateTime.now().toString(), Login.class.getName(), "CASHIER LOGIN", Roles.CASHIER.name(), LogType.INFO));

                        
                    }
                }

                Dashboard dashboard = new Dashboard(auth);
                dashboard.setVisible(true);

            } else {
                
                appLogger.WriteLog.log(new AppLog(LocalDateTime.now().toString(), Login.class.getName(), "Login failed, Incorrect username or password", "annonymouse", LogType.INFO));

                JOptionPane.showMessageDialog(this, "Invalid username or password", "Login Error", JOptionPane.ERROR_MESSAGE);
            }

        } catch (SQLException e) {
            appLogger.WriteLog.log(new AppLog(LocalDateTime.now().toString(), Login.class.getName(),"Database Connection issue", "annonymouse", LogType.ERROR));

            
            JOptionPane.showMessageDialog(this, "Database Error : Contact Developer", "System Falier", JOptionPane.ERROR_MESSAGE);

        }

    }//GEN-LAST:event_btn_loginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        // Set the path to your log4j2 configuration file

//        print java version JDK and jre
        String log4jConfigFile = "file:///C:/SitharaSuper/log4j2.xml";

        // Configure Log4j2
        

//Log this variables and programm stat time
        String javaVersion = System.getProperty("java.version");
        String javaVendor = System.getProperty("java.vendor");
        String jreVersion = System.getProperty("java.runtime.version");
        String jdkVersion = System.getProperty("java.vm.version");

        System.out.println("JDK version: " + jdkVersion);
        System.out.println("JRE version: " + jreVersion);

       

        com.formdev.flatlaf.themes.FlatMacLightLaf.setup();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_login;
    private javax.swing.ButtonGroup buttonGroupRoleMode;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRB_admin;
    private javax.swing.JRadioButton jRB_cachier;
    private javax.swing.JTextField tf_email;
    private javax.swing.JPasswordField tf_password;
    // End of variables declaration//GEN-END:variables
}
